language: python
python:
  - "3.6"
# env:
#   - TESTDUDE='True'
install:
  - pip install -r spirit/requirements.txt
script:
  - coverage run spirit/manage.py test api
after_success:
  - bash <(curl -s https://codecov.io/bash)
