version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
#    ports: 
#      - "5555:5432"
    volumes:
      - data/var/lib/postgresql/data
  spirit:
    build: spirit/.
    volumes:
      - ./spirit/:/app/
    ports:
      - "8420:8420"
    links:
      - db

volumes:
  data: {}
