version: '3'

services:
  db:
    # image: postgres
    restart: always
    environment:
      - POSTGRES_DB=pizzaspirit
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=admin
    build: ./postgres/.

  spirit:
    build: spirit/.
    restart: always
    volumes:
      - ./spirit/:/app/
    ports:
      - "8420:8420"
    links:
      - db
