# Generated by Django 3.1.3 on 2020-11-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20201125_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaorder',
            name='customer',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='flavor',
            field=models.CharField(choices=[('Margarita', 'margarita'), ('Marinara', 'marinara'), ('Salami', 'salami')], max_length=16),
        ),
    ]
