# Generated by Django 3.1.3 on 2020-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_pizzaorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='flavor',
            field=models.IntegerField(choices=[('Margarita', 'margarita'), ('Marinara', 'marinara'), ('Salami', 'salami')]),
        ),
    ]
