# Generated by Django 3.1.3 on 2020-11-25 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza', '0006_auto_20201125_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaorder',
            name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(related_name='pizzas', to='pizza.PizzaOrder'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='flavor',
            field=models.IntegerField(choices=[('Margarita', 'margarita'), ('Marinara', 'marinara'), ('Malami', 'salami')]),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizza.pizza'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
