# Generated by Django 3.1.3 on 2020-11-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20201125_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cooking',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='moving',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='flavor',
            field=models.CharField(choices=[('Margarita', 'margarita'), ('Marinara', 'marinara'), ('Malami', 'salami')], max_length=42),
        ),
    ]
