# Generated by Django 3.1.3 on 2020-11-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20201125_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizza.pizzaorder'),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='pizza_order',
            field=models.ManyToManyField(related_name='pizzas', to='pizza.Order'),
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('cooking', models.BooleanField(default=False)),
                ('moving', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_state', to='pizza.order')),
            ],
        ),
    ]
