# Generated by Django 3.1.3 on 2020-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_auto_20201125_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(related_name='pizzas', to='pizza.PizzaOrder'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='flavor',
            field=models.CharField(choices=[('Margarita', 'margarita'), ('Marinara', 'marinara'), ('Salami', 'salami')], max_length=42),
        ),
    ]
