# Generated by Django 3.1.3 on 2020-11-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_auto_20201125_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza',
        ),
        migrations.AddField(
            model_name='orderstate',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_state', to='pizza.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizza.pizzaorder'),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='pizza_order',
            field=models.ManyToManyField(related_name='pizzas', to='pizza.Order'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='flavor',
            field=models.CharField(choices=[('Margarita', 'margarita'), ('Marinara', 'marinara'), ('Malami', 'salami')], max_length=42),
        ),
    ]
