# Generated by Django 3.1.3 on 2020-11-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0013_auto_20201125_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstate',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza_order',
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='pizza.PizzaOrder'),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='flavor',
            field=models.CharField(choices=[('Margarita', 'margarita'), ('Marinara', 'marinara'), ('Salami', 'salami')], max_length=42),
        ),
    ]
