# Generated by Django 3.1.3 on 2020-11-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0014_auto_20201125_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_state', to='pizza.orderstate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(related_name='pizzas', to='pizza.PizzaOrder'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizza.pizza'),
        ),
    ]
